[theme]
base = "light"
primaryColor = "#0f172a"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f5f7"
textColor = "#1f2937"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
